name: Check Markdown links

on:
    push:
        branches:
        - main

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: byrnereese/github-action-mkdocs-link-check@1.0
      with:
        use-verbose-mode: 'yes'
        folder-path: '.'